### PR TITLE
Make caching configurable; fixes #19

### LINKED ISSUE #19: Improve caching support
This was first reported by Joanna Beaver at https://moodle.org/plugins/local_course_template. This plugin uses an internal cache so that during bulk course creation a course is only backed up once. The effective life of the backup is a maximum of 24 hours because there's a daily scheduled task that removes all backups created by this plugin. That's unhelpful if you're testing the plugin and making changes to your template course because the backup will not be updated until it's removed by the task.

### PR DESCRIPTION
**Pull request by mackensen**

### CODE REVIEW

**Comment by andyzito** [comment]
@mackensen I presume you've tested this?

**Comment by mackensen** [comment]
@azito122 Yes. I stepped through this testing regime:

1. Created a template course with Label A. Caching is enabled.
1. Created Course 1; confirmed Course 1 has Label A.
1. Modified the template course to add Label B.
1. Created Course 2; confirmed Course 2 has Label A and not Label B.
1. Disabled caching.
1. Created Course 3; confirmed Course 3 has Label A and Label B.

That said, I've just realized there's a bug. If you go to enable caching and create Course 4...you still only get Label A, because the old cache was never invalidated. Disabling caching should probably purge the cache as well?

**Comment by andyzito** [comment]
@mackensen Yes, I think that would be the way to go.

**Comment by andyzito** [comment]
@mackensen Looks good to me. Fix the one indentation error I commented and the other codechecker errors, and assuming you've tested it, it's good to go.

**Comment by andyzito** [comment]
We believe the test failures are due to some bizarre environmental race condition on Travis. I've reviewed the code and run the test locally, and this is ready to merge.

**Pull request merged**
